#!/bin/bash
# ------------------------------------------------------------------
# [Shaurita Hutchins] pipcleanup
#          This cleans up or deletes the pip cache.

# Cleanup your pip cache

rm -r ~/.cache/pip/*

echo "INFO: Pip cache has been cleaned."